include: package:lints/recommended.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
