name: openapi
description: OpenAPI (Swagger) data structures and class library written in Dart.
version: 0.0.1
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_openapi

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.16.6
  lints: ^1.0.0
